find_path (MNL_INCLUDE_DIR NAMES libmnl/libmnl.h)
find_library(MNL_LIBRARY NAMES mnl libmnl)

include(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibMNL REQUIRED_VARS MNL_LIBRARY MNL_INCLUDE_DIR)

MARK_AS_ADVANCED(MNL_LIBRARY MNL_INCLUDE_DIRS)
